url: https://test-stand.gb.ru/gateway/login
address: https://test-stand.gb.ru/api/posts
address_post: https://test-stand.gb.ru/gateway/posts

login: vlad_d
pswd: b1b27ba7f4

title: New_title
description: New_description_for_test_HW
content: content_content_content_content_content_content_content_content_content_content_content_content_